version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: trustmall
      POSTGRES_PASSWORD: trustmallpass
      POSTGRES_DB: trustmall_dev
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: